{
    'name': 'Product ID Number',
    'version': '19.0.1.0.0',
     'summary': 'Product ID Number is a powerful Odoo extension that introduces a dedicated unique ID field for products and ensures its visibility across Purchase, Sales, Inventory, and PDF reports.',
    'description': """
         Product ID Number is a practical and powerful Odoo extension that adds a dedicated unique Product ID field to your product records and ensures its visibility across major business workflows. Many organizations require a structured or numeric product identification system beyond the default internal reference, especially for compliance, reporting accuracy, warehouse control, and audit clarity. This module introduces a custom Product ID Number field in the product form and automatically integrates it into Purchase, Sales, and Inventory operations.
    """,
    'author': 'NexvantaTech',
    'website': 'https://nexvantatech.com',
    'category': 'Sales',
    'depends': ['product', 'sale', 'account', 'purchase', 'stock'], 
    'data': [
        'views/product_view.xml',
        'views/sale_view.xml',
        'views/invoice_view.xml',
        'views/purchase_view.xml',
        'views/stock_view.xml', 
        'report/invoice_report_template.xml',
        'report/purchase_report_template.xml',
        'security/ir.model.access.csv',
    ],

   'images': ['static/description/Banner.png'],
    'images': ['static/description/1.png'],
    'images': ['static/description/2.png'],
    'images': ['static/description/3.png'],
    'images': ['static/description/4.png'],
    'images': ['static/description/5.png'],
    'images': ['static/description/6.png'],
    'images': ['static/description/7.png'],
    'images': ['static/description/8.png'],
    'images': ['static/description/9.png'],
    'images': ['static/description/10.png'],
    'images': ['static/description/icon.png'],
     "documentation": ["static/description/index.html"],
    'license': 'OPL-1',
    "live_test_url": "https://www.youtube.com/watch?v=Lk7ix8I2yh0",
    'price': 6.00,
    'currency': 'USD',
    'installable': True,
    'application': True,
    'auto_install': False,

}